export const Classes: { [key: string]: string[] } = {
    'Arachnida': [
        'Acari',
        'Araneae',
        'Amblypygi',
        'Opiliones',
        'Pseudoscorpiones',
        'Scorpions',
        'Solifugae',
        'Thelyphonida',
    ],
    'Insecta': [
        'Archaeognatha',
        'Blattodea',
        'Coleoptera',
        'Dermaptera',
        'Diptera',
        'Embioptera',
        'Ephemeroptera',
        'Hemiptera',
        'Hymenoptera',
        'Isoptera',
        'Lepidoptera',
        'Mantodea',
        'Mecoptera',
        'Megaloptera',
        'Neuroptera',
        'Odonata',
        'Orthoptera',
        'Phasmida',
        'Plecoptera',
        'Psocoptera',
        'Raphidioptera',
        'Thysanoptera',
        'Trichoptera',
        'Zygentoma',
    ]
}
